
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - my-network

  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks:
      - my-network

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
    networks:
      - my-network


  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # OTLP HTTP endpoint
      - "4317:4317"   # OTLP gRPC endpoint
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - my-network

  reddit-service:
    image: quarkus/reddit-improved-api-jvm
#    platform: linux/amd64
    container_name: reddit-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - opensearch
      - kafka1
      - jaeger
    environment:
      - MP_MESSAGING_OUTGOING_REDDIT_POSTS_BOOTSTRAP_SERVERS=kafka1:19092
      - MP_MESSAGING_INCOMING_REDDIT_POSTS_CONSUMER_BOOTSTRAP_SERVERS=kafka1:19092
      - QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS=kafka1:19092
      - QUARKUS_KAFKA_STREAMS_APPLICATION_SERVER=kafka1:19092
      - QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317

    networks:
      - my-network
volumes:
  mongodb_data:
networks:
  my-network:
    driver: bridge
